name: Update 3GPP Mobile Gateways

on:
  push:
    branches:
      - master
  schedule:
    - cron: "00 0,6,12,18 * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Generate URIs.
        run:  |
          out="$(curl -s https://mcc-mnc.net/mcc-mnc.csv | awk -F';' '{print$1" "$2}' | while read -r mcc mnc; do \
            echo "epdg.epc.mnc"${mnc}".mcc"${mcc}".pub.3gppnetwork.org"; done)"
          if [[ -n "${out}" ]]; then echo "${out}" > 3gpp_domains.txt; fi
      - name: Get all IPv4 addresses by looping DNS.
        run:  |
          rm -f 3gpp_4.txt; touch 3gpp_4.txt
          ip4regex="((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])"
          while read -r mcc mnc; do
            out="$(dig +short @1.1.1.1 -t A "epdg.epc.mnc${mnc}.mcc${mcc}.pub.3gppnetwork.org")"
            if [[ "${out}" =~ "^${ip4regex}$" ]]; then echo "${out}" >> 3gpp_4.txt; fi
          done < 3gpp_domains.txt
      - name: Get all IPv6 addresses by looping DNS.
        run:  |
          ipregex='(([0-9a-fA-F]{1,4}:){7,7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|\
            ([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|\
            ([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|\
            [0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7}|:)|fe80:(:[0-9a-fA-F]{0,4}){0,4}%[0-9a-zA-Z]{1,}|\
            ::(ffff(:0{1,4}){0,1}:){0,1}((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])|\
            ([0-9a-fA-F]{1,4}:){1,4}:((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9]))'
          ip6regex="$(printf '%s' "${ipregex//[[:space:]]/}" | sed 's/\|\\//g')"
          while read -r mcc mnc; do
            out="$(dig +short @1.1.1.1 -t AAAA "epdg.epc.mnc${mnc}.mcc${mcc}.pub.3gppnetwork.org")"
            if [[ "${out}" =~ "^${ip6regex}$" ]]; then echo "${out}" >> 3gpp_6.txt; fi
          done < 3gpp_domains.txt
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d - %H:%M:%S')"
      - name: Upload Stuff to GitHub via https://github.com/stefanzweifel/git-auto-commit-action
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          file_pattern: '*.txt'
          disable_globbing: true
          commit_message: Update 3GPP Lists - ${{ steps.date.outputs.date }}
