name: Update 3GPP Mobile Gateways

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "00 1 * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Set up Python
        uses: actions/setup-python@main
        with:
          python-version: '3.x'
          check-latest: true
          #cache: 'pip'
      - name: Installiere Python-AbhÃ¤ngigkeiten
        run: |
          pip3 install requests pandas dnspython
      - name: Create Backup.
        run: |
          curl -s https://mcc-mnc.net/mcc-mnc.csv > /tmp/mcc-mnc.csv; \
            if [[ $(grep -c ".*" /tmp/mcc-mnc.csv) -gt 100 ]]; then mv /tmp/mcc-mnc.csv mcc-mnc.csv; fi
      - name: Generate outputs
        run: python3 resolve.py
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d - %H:%M:%S')"
      - name: Upload Stuff to GitHub via https://github.com/stefanzweifel/git-auto-commit-action
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          file_pattern: '*.txt *.csv'
          disable_globbing: true
          commit_message: Update 3GPP Lists - ${{ steps.date.outputs.date }}
